# Generated by Django 4.2.9 on 2025-09-17 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_number', models.TextField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('rooms_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('availability_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'apartments',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField(blank=True, null=True)),
                ('floors', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'buildings',
            },
        ),
        migrations.CreateModel(
            name='MediaApartment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('panorama', 'Panorama'), ('pdf', 'PDF'), ('video', 'Video')], max_length=20)),
                ('url', models.TextField()),
                ('alt_text', models.TextField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('filesize_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='main.building')),
            ],
            options={
                'db_table': 'media_apartment',
            },
        ),
        migrations.CreateModel(
            name='PolygonJson',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('coords', models.JSONField()),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygons', to='main.apartment')),
                ('media_apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygons', to='main.mediaapartment')),
            ],
            options={
                'db_table': 'polygons_json',
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='main.building'),
        ),
    ]
