# Generated by Django 4.2.9 on 2025-09-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_building_floors_building_brochure_media_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_image',
            field=models.ImageField(blank=True, null=True, upload_to='buildings/'),
        ),
    ]
