# Generated by Django 4.2.9 on 2025-09-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_building_building_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaapartment',
            name='url',
            field=models.ImageField(upload_to='buildings/'),
        ),
    ]
